# Run Continuous Integration on every push
# This tests Python 3.9
name: python_compatibility_3.9
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Python 3.9 eggs
      uses: actions/cache@v1
      with:
        path: ${{ github.workspace }}/.eggs
        key: python-compatibility-3.9-eggs

    - name: Run tests on 3.9 latest
      run: docker run -v "${GITHUB_WORKSPACE}:/home/yatiml" python:3.9 /bin/bash -c 'cd /home/yatiml && pip install -U pip setuptools wheel ruamel.yaml==0.16.12 && python setup.py test'
